files = {
	coins = "coins.dat",
	score = "score.dat",
	skins = "skins.dat"
}

files.customskins = {}

files.customskins.readme = [[
! (this file is automatically generated upon game execution) !


HOW TO ADD YOUR CUSTOM SKINS:

1 Data Structure:
	You need a couple of files to get started.
	Skins are added by creating a directory in customskins/

	1.1 Directory Name:
		Your directory name will be the skin id. The ID is not visible to the
		player and is unique for every skin.
		Make sure not to use an already used ID by the main game, as it will
		be replaced.

	1.2 Image Files:
		These files will be displayed for the bird animation.
		Image Files should all be in a .jpg format. The file names should be:

		1.jpg (the idle state of the skin)
		2.jpg (the jump/flop state of the skin)
		3.jpg (the dead state of the skin)

		Only the first image in mandatory, as missing images will be replaced
		by it.
		If 1.jpg is missing, it will be replaced by a "missing texture"-image.

	1.3 Data Files:
		The data files are what specify the name, price, description of
		your skin.
		Create 3 files: "price.txt", "desc.txt" and "name.txt"
		
		Simply put an integer in price.txt, and strings in the other two files.
		This will be imported upon the start of the game.

		If the files are not provided, the files will fall back to a failsafe:
		 > Price will be:       999
		 > Name will be:        "Custom Skin"
		 > Description will be: "Custom Skin Description"



2 Example of a skin:
	my_cool_skin_folder
	 → name.txt
	 → desc.txt
	 → price.txt
	 → 1.jpg
	 → 2.jpg
	 → 3.jpg



3 Ending Words:
	I hope this has been a helpful resource :)
	Have fun adding wacky and beautiful skins!

]]

return files
